// tailwind-config.js
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary": "#10257b",
                "success": "#8EF0A9",
                "secondary-fixed": "#d9e2ff",
                "surface-container-highest": "#e3e1e9",
                "tertiary": "#512200",
                "secondary-container": "#79a1fe",
                "border-subtle": "#E2E8F0",
                "inverse-on-surface": "#f2f0f8",
                "on-error-container": "#93000a",
                "surface-variant": "#e3e1e9",
                "surface-container-lowest": "#ffffff",
                "secondary": "#2e5bb3",
                "surface-container-low": "#f5f2fa",
                "primary-fixed": "#dee1ff",
                "on-secondary": "#ffffff",
                "inverse-surface": "#303036",
                "error-container": "#ffdad6",
                "primary-fixed-dim": "#b9c3ff",
                "on-surface": "#1b1b21",
                "on-primary-container": "#a0afff",
                "on-tertiary-fixed": "#321300",
                "surface-container-high": "#e9e7ef",
                "on-primary": "#ffffff",
                "inverse-primary": "#b9c3ff",
                "surface-bright": "#fbf8ff",
                "on-secondary-fixed-variant": "#06429a",
                "surface-tint": "#4658ad",
                "surface-container": "#efedf5",
                "on-background": "#1b1b21",
                "text-main": "#0F1115",
                "secondary-fixed-dim": "#b0c6ff",
                "on-secondary-fixed": "#001945",
                "tertiary-fixed": "#ffdbc8",
                "on-surface-variant": "#454651",
                "on-secondary-container": "#003581",
                "surface": "#FFFFFF",
                "background": "#fbf8ff",
                "tertiary-fixed-dim": "#ffb68a",
                "on-tertiary": "#ffffff",
                "on-error": "#ffffff",
                "outline": "#757683",
                "on-primary-fixed-variant": "#2d3f93",
                "accent-vowel": "#95F2C3",
                "error": "#FF7D7D",
                "tertiary-container": "#733400",
                "on-tertiary-fixed-variant": "#743501",
                "on-primary-fixed": "#001258",
                "surface-dim": "#dbd9e1",
                "text-muted": "#64748B",
                "primary-container": "#2c3e92",
                "outline-variant": "#c5c5d3",
                "on-tertiary-container": "#f99e64"
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            spacing: {
                "pill-padding-y": "0.5rem",
                "component-gap": "1rem",
                "section-gap": "4rem",
                "safe-area": "2rem",
                "gutter": "1.5rem",
                "pill-padding-x": "1.25rem"
            },
            fontFamily: {
                "stats-label": ["Inter"],
                "body-base": ["Inter"],
                "ui-label": ["Inter"],
                "stats-value": ["Inter"],
                "word-display": ["Inter"],
                "nav-pill": ["Inter"],
                "word-display-mobile": ["Inter"]
            },
            fontSize: {
                "stats-label": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                "body-base": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "ui-label": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
                "stats-value": ["14px", {"lineHeight": "20px", "fontWeight": "700"}],
                "word-display": ["72px", {"lineHeight": "1.1", "letterSpacing": "0.02em", "fontWeight": "800"}],
                "nav-pill": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
                "word-display-mobile": ["44px", {"lineHeight": "1.1", "letterSpacing": "0.02em", "fontWeight": "800"}]
            }
        },
    },
}